name: Deploy CI workflow

on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./front-end/unirent
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run build
            - run: npm start
